version: '3'
services:
  php_web:
    image: shelter2024/zzzcms-v2.1.7-web  
    container_name: zzzcms-v2.1.7-web
    depends_on:
      - mysql
    ports:
      - "80:80"
  mysql:
    image: mysql:5.7
    container_name: zzzcms-v2.1.7-web-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=zzzcms
