version: '3'
services:
  php_web:
    image: shelter2024/yzmcms-v7.0-web
    container_name: yzmcms-v7.0-web
    depends_on:
      - mysql
    ports:
      - "80:80"
  mysql:
    image: mysql:5.7
    container_name: yzmcms-v7.0-web-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=yzmcms
    volumes:
      - ./database.sql:/docker-entrypoint-initdb.d/init.sql
