version: '3'
services:
  java_web:
    image: shelter2024/spiderflow-v0.5.0-web
    container_name: Spiderflow-v0.5.0-web
    depends_on:
      - mysql
    ports:
      - "8080:8080"
  mysql:
    image: mysql:5.7
    container_name: Spiderflow-v0.5.0-web-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports: 
      - 3306:3306
    volumes:
      - ./sqldata/spiderflow.sql:/docker-entrypoint-initdb.d/init.sql
